### ISSUE TITLE
Failed to execute 'compile' on 'WebAssembly'

### ISSUE THREAD

**Issue by dmitrievav** [bitnami/nami#38] opened 2019-08-18 14:40 UTC
Hi!

I could not understand where apache pkg exactly comes from =(
but it misses `AddType application/wasm .wasm`
which leads to:
```
Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
```

the same issue described here: https://bz.apache.org/bugzilla/show_bug.cgi?id=63162

Maybe we have to update apache or just make a work around:
```
echo -e "application/wasm\t\t\t\twasm" >> /opt/bitnami/apache/conf/mime.types
```

Here is my version of apach pkg:
```
root@wordpress-9f9b8cd55-29bnt:/# nami inspect com.bitnami.apache
{
  "id": "com.bitnami.apache",
  "name": "apache",
  "version": "2.4.39",
  "revision": "2",
  "installedAsRoot": false,
  "lifecycle": "installed",
  "installdir": "/opt/bitnami/apache",
  "installPrefix": "/opt/bitnami",
```

And here is wordpress helm version:
```
NAME                	REVISION	UPDATED                 	STATUS  	CHART                     	APP VERSION	NAMESPACE
wordpress           	1       	Sun Aug 11 17:35:33 2019	DEPLOYED	wordpress-7.1.0           	5.2.2      	wordpress
```

**Comment by juamedgod** [comment] 2019-08-19 11:19
Hi,

The issue does not seem related to nami. Could you report it in the [ Bitnami Apache Docker Image](https://github.com/bitnami/bitnami-docker-apache )
 repository? 

Thanks for reporting!

**Comment by dmitrievav** [comment] 2019-08-22 12:12
Hi! I believe it is not related to docker image, but to nami apache package. Could you help me to understand where nami packages come from ?

**Comment by juamedgod** [comment] 2019-08-26 15:06
As you mention, the issue is in the nami Apache package but it does not seem to be related to a nami bug but to a misconfiguration in the Apache module (nami is just the generic tool used to install the packages).

We do not have a specific public repository for the Apache nami module but the [Bitnami Apache Docker Image](https://github.com/bitnami/bitnami-docker-apache) repository should be a good place to track the issue.

**Comment by marcosbc** [comment] 2022-01-24 16:55
Hi all, it has been some time since we removed Nami usage from Bitnami container images, so I'll close this issue as it is not applicable anymore.

**Closed by marcosbc** 2022-01-24 16:55 UTC
